# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-ClearSilver
version:      0.01
version_from: lib/Apache/ClearSilver.pm
installdirs:  site
requires:
    Apache::ModuleConfig:          0
    ClearSilver:                   0
    mod_perl:                      1.2
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
